// Package types provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package types

// HttpErrorResponse defines model for HttpErrorResponse.
type HttpErrorResponse struct {

	// I18N Error message.
	Msg string `json:"msg"`
}
